apiVersion: v1
kind: Service
metadata:
  name: machines-frontend
spec:
  selector:
    app: machines-frontend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
